//created on: Nov 12, 2016
package org.acme.insurance.policyquote

//list any import classes here.
import org.acme.insurance.Driver
import org.acme.insurance.Policy


rule "RiskyYouths"
    ruleflow-group "calculation"
    when
        //conditions
        driver : Driver( age >= 18 && < 25, numberOfAccidents >= 1 || numberOfTickets >= 2 )
        policy : Policy( price == null, policyType == "AUTO" )
    then
        //actions
        modify(policy){setPrice(700)};
        System.out.println("fired rule "+ kcontext.getRule().getName());
end