//created on: Nov 12, 2016
package org.acme.insurance.policyquote

import org.acme.insurance.Driver
import org.acme.insurance.Policy

rule "SafeYouths"
    ruleflow-group "calculation"
    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfTickets <= 1, numberOfAccidents < 1 )
        policy : Policy( price == null, policyType == "AUTO" )
    then
        //actions
        modify(policy){setPrice(450)};
        System.out.println("fired rule "+ kcontext.getRule().getName());

end